import fs from 'fs';
import path from 'path';

async function runFastForensicAudit() {
  console.log('===========================================================');
  console.log('  FAST READ-ONLY FORENSIC AUDIT OF PHONE CLEANUP REVIEWS ');
  console.log('===========================================================\n');

  const planPath = path.join(process.cwd(), 'scratch', 'phase3-cleanup-plan.json');
  const storePath = path.join(process.cwd(), 'scratch', 'phone-cleanup-reviews-store.json');

  if (!fs.existsSync(storePath)) {
    console.log('❌ phone-cleanup-reviews-store.json does NOT exist on disk.');
    return;
  }

  const storeRaw = fs.readFileSync(storePath, 'utf-8');
  const storeObj = JSON.parse(storeRaw);
  const parents = storeObj.parents || {};
  const items = storeObj.items || {};

  const parentPhones = Object.keys(parents);
  console.log(`Total phone groups in store: ${parentPhones.length}`);

  let automatedCount = 0;
  let customUserCount = 0;
  const customUserGroups: any[] = [];

  parentPhones.forEach(phone => {
    const p = parents[phone];
    const itemMap = items[phone] || {};

    // Check if reviewedBy or reviewerComment or any item was edited manually
    const isAutoPlan = p.reviewedBy === 'Coordinador General' && p.reviewerComment?.includes('Plan de saneamiento pre-evaluado');

    if (isAutoPlan) {
      automatedCount++;
    } else {
      customUserCount++;
      customUserGroups.push({ phone, parent: p, items: itemMap });
    }
  });

  console.log(`\nAudit Results:`);
  console.log(`- Pre-calculated Automated Plan Groups: ${automatedCount}`);
  console.log(`- Custom User Manual Review Groups Found: ${customUserCount}`);

  if (customUserGroups.length > 0) {
    console.log('\n⭐ CUSTOM USER MANUAL DECISIONS FOUND:');
    customUserGroups.forEach(g => {
      console.log(`\nPhone: ${g.phone}`);
      console.log(`Reviewer: ${g.parent.reviewedBy}`);
      console.log(`Comment: ${g.parent.reviewerComment}`);
      console.log(`Status: ${g.parent.reviewStatus}`);
      console.log(`Items:`, JSON.stringify(g.items, null, 2));
    });
  } else {
    console.log('\n⚠️ No custom user reviewer comments or manual overrides were found in store.json.');
    console.log('All 59 groups currently reflect the pre-populated algorithmic plan generated by phase3-cleanup-plan.json.');
  }

  console.log('\n===========================================================');
  console.log('  FORENSIC AUDIT COMPLETED. NO DATA WAS MODIFIED.');
  console.log('===========================================================');
}

runFastForensicAudit().catch(console.error);
